# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/smdp/xup/Day-1_fpga_flow/D1L3/D1L3.cache/wt [current_project]
set_property parent.project_path F:/smdp/xup/Day-1_fpga_flow/D1L3/D1L3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  F:/smdp/xup/Day-1_fpga_flow/lab2/sources/uart_baud_gen.v
  F:/smdp/xup/Day-1_fpga_flow/lab2/sources/uart_rx_ctl.v
  F:/smdp/xup/Day-1_fpga_flow/lab2/sources/meta_harden.v
  F:/smdp/xup/Day-1_fpga_flow/lab2/sources/uart_rx.v
  F:/smdp/xup/Day-1_fpga_flow/lab2/sources/led_ctl.v
  F:/smdp/xup/Day-1_fpga_flow/lab2/sources/uart_led.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/smdp/xup/Day-1_fpga_flow/lab2/sources/uart_led_pins_basys3.xdc
set_property used_in_implementation false [get_files F:/smdp/xup/Day-1_fpga_flow/lab2/sources/uart_led_pins_basys3.xdc]

read_xdc F:/smdp/xup/Day-1_fpga_flow/lab2/sources/uart_led_timing.xdc
set_property used_in_implementation false [get_files F:/smdp/xup/Day-1_fpga_flow/lab2/sources/uart_led_timing.xdc]


synth_design -top uart_led -part xc7a35tcpg236-1


write_checkpoint -force -noxdef uart_led.dcp

catch { report_utilization -file uart_led_utilization_synth.rpt -pb uart_led_utilization_synth.pb }
