# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/smdp/xup/Day-1_fpga_flow/D1L1/D1L1.cache/wt [current_project]
set_property parent.project_path F:/smdp/xup/Day-1_fpga_flow/D1L1/D1L1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_verilog -library xil_defaultlib F:/smdp/xup/Day-1_fpga_flow/lab1/sources/lab1.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/smdp/xup/Day-1_fpga_flow/lab1/sources/lab1_basys3.xdc
set_property used_in_implementation false [get_files F:/smdp/xup/Day-1_fpga_flow/lab1/sources/lab1_basys3.xdc]


synth_design -top lab1 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab1.dcp

catch { report_utilization -file lab1_utilization_synth.rpt -pb lab1_utilization_synth.pb }
